# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="django_vue_generator",
    version="0.1.0",
    description="Generates vue frontend for django rest framework projects.",
    python_requires="==3.*,>=3.7.0",
    project_urls={"homepage": "https://github.com/pawnhearts/django_vue_generator"},
    author="ph",
    author_email="robotnaoborot@gmail.com",
    packages=[
        "django_vue_generator",
        "django_vue_generator.management",
        "django_vue_generator.migrations",
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "django==2.*,>=2.2.0",
        "django-filter==2.*,>=2.2.0",
        "djangorestframework==3.*,>=3.10.0",
    ],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"]},
)
